import { type DraftResponse, type Critique, type Synthesis } from "@shared/schema";

export function synthesize(
  question: string,
  drafts: DraftResponse[],
  critiques: Critique[]
): Synthesis {
  console.log("[Council] Synthesizing consensus...");

  const allClaims = new Map<string, {
    text: string;
    sources: Set<string>;
    supporters: Set<string>;
    confidence: number[];
  }>();

  for (const draft of drafts) {
    for (const claim of draft.claims) {
      const normalized = claim.text.toLowerCase().trim();
      const existing = allClaims.get(normalized);
      
      if (existing) {
        existing.supporters.add(draft.agent);
        existing.confidence.push(draft.confidence);
        claim.support.forEach(src => existing.sources.add(src));
      } else {
        allClaims.set(normalized, {
          text: claim.text,
          sources: new Set(claim.support),
          supporters: new Set([draft.agent]),
          confidence: [draft.confidence],
        });
      }
    }
  }

  const critiquesByTarget = new Map<string, Set<string>>();
  for (const critique of critiques) {
    if (critique.issues.length > 0) {
      if (!critiquesByTarget.has(critique.target)) {
        critiquesByTarget.set(critique.target, new Set());
      }
      critique.issues.forEach(issue => 
        critiquesByTarget.get(critique.target)?.add(issue)
      );
    }
  }

  const decision_log: string[] = [];
  const finalClaims: string[] = [];
  const finalCitations = new Set<string>();
  const dissent: Array<{ point: string; who: string[] }> = [];

  const claimEntries = Array.from(allClaims.entries());
  
  for (const [normalized, data] of claimEntries) {
    const supportCount = data.supporters.size;
    const avgConfidence = data.confidence.reduce((a, b) => a + b, 0) / data.confidence.length;
    
    const targetCritiques = critiquesByTarget.get(data.supporters.values().next().value) || new Set();
    const hasCritiques = Array.from(targetCritiques).some(issue =>
      issue.toLowerCase().includes(normalized.slice(0, 20))
    );

    if (supportCount >= 3 && avgConfidence >= 0.6 && !hasCritiques) {
      finalClaims.push(data.text);
      data.sources.forEach(src => finalCitations.add(src));
      decision_log.push(
        `Kept: "${data.text.slice(0, 60)}..." (${supportCount}/4 models agreed, avg confidence: ${(avgConfidence * 100).toFixed(0)}%)`
      );
    } else if (supportCount >= 2 && avgConfidence >= 0.7 && !hasCritiques) {
      finalClaims.push(data.text);
      data.sources.forEach(src => finalCitations.add(src));
      decision_log.push(
        `Included: "${data.text.slice(0, 60)}..." (${supportCount}/4 models, high confidence: ${(avgConfidence * 100).toFixed(0)}%)`
      );
    } else if (supportCount === 1 || hasCritiques) {
      const dissenterNames = Array.from(data.supporters);
      decision_log.push(
        `Dropped: "${data.text.slice(0, 60)}..." (only ${supportCount}/4 models${hasCritiques ? ', flagged by critique' : ''})`
      );
      
      if (supportCount === 1 && avgConfidence >= 0.7) {
        dissent.push({
          point: data.text,
          who: dissenterNames as any[],
        });
      }
    } else {
      decision_log.push(
        `Excluded: "${data.text.slice(0, 60)}..." (insufficient consensus: ${supportCount}/4, confidence: ${(avgConfidence * 100).toFixed(0)}%)`
      );
    }
  }

  const summary = finalClaims.length > 0
    ? finalClaims.join(" ")
    : "The AI models could not reach a sufficient consensus on this question. Please try rephrasing or providing more context.";

  const avgDraftConfidence = drafts.reduce((sum, d) => sum + d.confidence, 0) / drafts.length;
  const consensusBonus = (finalClaims.length / Math.max(1, claimEntries.length)) * 0.2;
  const critiquesPenalty = critiques.filter(c => c.issues.length > 0).length * 0.05;
  
  const finalConfidence = Math.min(
    1,
    Math.max(
      0,
      avgDraftConfidence + consensusBonus - critiquesPenalty
    )
  );

  if (decision_log.length === 0) {
    decision_log.push("No claims were generated by the models. The question may be too ambiguous or complex.");
  }

  return {
    summary,
    confidence: finalConfidence,
    citations: Array.from(finalCitations).slice(0, 10),
    decision_log,
    dissent,
  };
}
