import { type DraftResponse, type Critique, type Synthesis } from "@shared/schema";

interface ClaimData {
  text: string;
  sources: Set<string>;
  supporters: Set<string>;
  confidences: Map<string, number>;
  critiques: Set<string>;
}

export function synthesize(
  question: string,
  drafts: DraftResponse[],
  critiques: Critique[]
): Synthesis {
  console.log("[Council] Synthesizing consensus...");

  const allClaims = new Map<string, ClaimData>();

  for (const draft of drafts) {
    for (const claim of draft.claims) {
      const normalized = claim.text.toLowerCase().trim();
      const existing = allClaims.get(normalized);
      
      if (existing) {
        existing.supporters.add(draft.agent);
        existing.confidences.set(draft.agent, draft.confidence);
        claim.support.forEach(src => existing.sources.add(src));
      } else {
        const confidences = new Map<string, number>();
        confidences.set(draft.agent, draft.confidence);
        
        allClaims.set(normalized, {
          text: claim.text,
          sources: new Set(claim.support),
          supporters: new Set([draft.agent]),
          confidences,
          critiques: new Set(),
        });
      }
    }
  }

  const critiqueMap = new Map<string, Critique[]>();
  for (const critique of critiques) {
    const key = critique.target;
    if (!critiqueMap.has(key)) {
      critiqueMap.set(key, []);
    }
    critiqueMap.get(key)!.push(critique);
  }

  for (const [normalized, claimData] of Array.from(allClaims.entries())) {
    for (const supporter of claimData.supporters) {
      const agentCritiques = critiqueMap.get(supporter) || [];
      
      for (const critique of agentCritiques) {
        for (const issue of critique.issues) {
          const issueLower = issue.toLowerCase();
          const claimSnippet = normalized.slice(0, 30);
          
          if (issueLower.includes(claimSnippet) || claimSnippet.includes(issueLower.slice(0, 30))) {
            claimData.critiques.add(`${critique.reviewer}: ${issue}`);
          }
        }
      }
    }
  }

  const decision_log: string[] = [];
  const finalClaims: string[] = [];
  const finalCitations = new Set<string>();
  const dissent: Array<{ point: string; who: string[] }> = [];

  const claimEntries = Array.from(allClaims.entries());
  
  if (claimEntries.length === 0) {
    decision_log.push("No claims were generated by the models. The question may be too ambiguous or complex.");
    
    return {
      summary: "The AI models could not generate structured responses for this question. Please try rephrasing or providing more context.",
      confidence: 0,
      citations: [],
      decision_log,
      dissent: [],
    };
  }

  for (const [normalized, data] of claimEntries) {
    const supportCount = data.supporters.size;
    const confidenceValues = Array.from(data.confidences.values());
    const avgConfidence = confidenceValues.reduce((a, b) => a + b, 0) / confidenceValues.length;
    const hasCritiques = data.critiques.size > 0;

    if (supportCount >= 3 && avgConfidence >= 0.5 && !hasCritiques) {
      finalClaims.push(data.text);
      data.sources.forEach(src => finalCitations.add(src));
      decision_log.push(
        `Kept: "${data.text.slice(0, 60)}..." (${supportCount}/4 models agreed, avg confidence: ${(avgConfidence * 100).toFixed(0)}%)`
      );
    } else if (supportCount >= 2 && avgConfidence >= 0.5 && !hasCritiques) {
      finalClaims.push(data.text);
      data.sources.forEach(src => finalCitations.add(src));
      decision_log.push(
        `Included: "${data.text.slice(0, 60)}..." (${supportCount}/4 models, high confidence: ${(avgConfidence * 100).toFixed(0)}%)`
      );
    } else if (supportCount >= 1 && avgConfidence >= 0.7 && !hasCritiques) {
      finalClaims.push(data.text);
      data.sources.forEach(src => finalCitations.add(src));
      decision_log.push(
        `Included: "${data.text.slice(0, 60)}..." (single model, very high confidence: ${(avgConfidence * 100).toFixed(0)}%)`
      );
    } else {
      const reasons: string[] = [];
      if (supportCount < 2) reasons.push(`only ${supportCount}/4 models`);
      if (avgConfidence < 0.6) reasons.push(`low confidence (${(avgConfidence * 100).toFixed(0)}%)`);
      if (hasCritiques) reasons.push(`${data.critiques.size} critique(s)`);
      
      decision_log.push(
        `Dropped: "${data.text.slice(0, 60)}..." (${reasons.join(", ")})`
      );
      
      if (supportCount === 1 && avgConfidence >= 0.7) {
        dissent.push({
          point: data.text,
          who: Array.from(data.supporters) as ("gpt5" | "claude" | "gemini" | "perplexity")[],
        });
      }
    }
  }

  const summary = finalClaims.length > 0
    ? finalClaims.join(" ")
    : "The AI models could not reach sufficient consensus on this question. Significant disagreement or low confidence prevented a unified answer.";

  let finalConfidence = 0;
  
  if (finalClaims.length > 0) {
    const keptClaims = claimEntries.filter(([normalized]) => 
      finalClaims.some(claim => claim.toLowerCase().includes(normalized.slice(0, 30)))
    );
    
    const confidenceSum = keptClaims.reduce((sum, [, data]) => {
      const values = Array.from(data.confidences.values());
      return sum + (values.reduce((a, b) => a + b, 0) / values.length);
    }, 0);
    
    const baseConfidence = keptClaims.length > 0 ? confidenceSum / keptClaims.length : 0;
    
    const consensusRatio = finalClaims.length / claimEntries.length;
    const consensusBonus = consensusRatio * 0.15;
    
    const totalCritiques = Array.from(allClaims.values()).reduce(
      (sum, data) => sum + data.critiques.size, 
      0
    );
    const critiquePenalty = Math.min(0.3, totalCritiques * 0.03);
    
    finalConfidence = Math.min(1, Math.max(0, baseConfidence + consensusBonus - critiquePenalty));
  }

  return {
    summary,
    confidence: finalConfidence,
    citations: Array.from(finalCitations).slice(0, 10),
    decision_log,
    dissent,
  };
}
