import { type DraftResponse, type Critique, type Synthesis, type ModelComparison } from "@shared/schema";

interface ClaimData {
  text: string;
  sources: Set<string>;
  supporters: Set<string>;
  confidences: Map<string, number>;
  critiques: Set<string>;
}

function buildModelComparisons(
  drafts: DraftResponse[],
  allClaims: Map<string, ClaimData>,
  finalClaimTexts: Set<string>
): ModelComparison[] {
  return drafts.map((draft) => {
    const draftClaimTexts = draft.claims.map((c) => c.text.toLowerCase().trim());

    // Claims this model made that ended up in the final answer
    const agreedClaims: string[] = [];
    // Claims this model made that no other model agreed with
    const uniqueClaims: string[] = [];
    // Claims from other models that this model's critiques flagged
    const contradictions: string[] = [];

    for (const claimText of draftClaimTexts) {
      const data = allClaims.get(claimText);
      if (!data) continue;

      if (finalClaimTexts.has(data.text)) {
        if (data.supporters.size > 1) {
          agreedClaims.push(data.text);
        } else {
          uniqueClaims.push(data.text);
        }
      } else if (data.supporters.size === 1 && data.supporters.has(draft.agent)) {
        uniqueClaims.push(data.text);
      }
    }

    // Surface contradictions: issues this model raised about others
    for (const [, data] of allClaims) {
      for (const critique of data.critiques) {
        if (critique.startsWith(`${draft.agent}:`)) {
          const issueText = critique.slice(draft.agent.length + 1).trim();
          if (!contradictions.includes(issueText)) {
            contradictions.push(issueText);
          }
        }
      }
    }

    // Build a per-model prose summary
    const summaryParts: string[] = [];
    if (agreedClaims.length > 0) {
      summaryParts.push(`Agreed on ${agreedClaims.length} shared claim(s).`);
    }
    if (uniqueClaims.length > 0) {
      summaryParts.push(`Contributed ${uniqueClaims.length} unique claim(s) not shared by other models.`);
    }
    if (contradictions.length > 0) {
      summaryParts.push(`Raised ${contradictions.length} issue(s) about other models' answers.`);
    }
    if (summaryParts.length === 0) {
      summaryParts.push("No claims contributed to the final answer.");
    }

    return {
      agent: draft.agent,
      summary: summaryParts.join(" "),
      confidence: draft.confidence,
      uniqueClaims: uniqueClaims.slice(0, 5),
      agreedClaims: agreedClaims.slice(0, 5),
      contradictions: contradictions.slice(0, 5),
    };
  });
}

export function synthesize(
  question: string,
  drafts: DraftResponse[],
  critiques: Critique[]
): Synthesis {
  console.log("[Council] Synthesizing consensus...");

  const allClaims = new Map<string, ClaimData>();

  for (const draft of drafts) {
    for (const claim of draft.claims) {
      const normalized = claim.text.toLowerCase().trim();
      const existing = allClaims.get(normalized);

      if (existing) {
        existing.supporters.add(draft.agent);
        existing.confidences.set(draft.agent, draft.confidence);
        claim.support.forEach((src) => existing.sources.add(src));
      } else {
        const confidences = new Map<string, number>();
        confidences.set(draft.agent, draft.confidence);

        allClaims.set(normalized, {
          text: claim.text,
          sources: new Set(claim.support),
          supporters: new Set([draft.agent]),
          confidences,
          critiques: new Set(),
        });
      }
    }
  }

  const critiqueMap = new Map<string, Critique[]>();
  for (const critique of critiques) {
    const key = critique.target;
    if (!critiqueMap.has(key)) {
      critiqueMap.set(key, []);
    }
    critiqueMap.get(key)!.push(critique);
  }

  for (const [normalized, claimData] of Array.from(allClaims.entries())) {
    for (const supporter of claimData.supporters) {
      const agentCritiques = critiqueMap.get(supporter) || [];

      for (const critique of agentCritiques) {
        for (const issue of critique.issues) {
          const issueLower = issue.toLowerCase();
          const claimSnippet = normalized.slice(0, 30);

          if (
            issueLower.includes(claimSnippet) ||
            claimSnippet.includes(issueLower.slice(0, 30))
          ) {
            claimData.critiques.add(`${critique.reviewer}: ${issue}`);
          }
        }
      }
    }
  }

  const decision_log: string[] = [];
  const finalClaims: string[] = [];
  const finalCitations = new Set<string>();
  const dissent: Array<{ point: string; who: string[] }> = [];

  const claimEntries = Array.from(allClaims.entries());
  const totalModels = drafts.length;

  if (claimEntries.length === 0) {
    decision_log.push(
      "No claims were generated by the models. The question may be too ambiguous or complex."
    );

    return {
      summary:
        "The AI models could not generate structured responses for this question. Please try rephrasing or providing more context.",
      confidence: 0,
      citations: [],
      decision_log,
      dissent: [],
      modelComparisons: [],
    };
  }

  const majorityThreshold = Math.ceil(totalModels / 2);

  for (const [normalized, data] of claimEntries) {
    const supportCount = data.supporters.size;
    const confidenceValues = Array.from(data.confidences.values());
    const avgConfidence =
      confidenceValues.reduce((a, b) => a + b, 0) / confidenceValues.length;
    const hasCritiques = data.critiques.size > 0;

    if (supportCount >= majorityThreshold + 1 && avgConfidence >= 0.5 && !hasCritiques) {
      finalClaims.push(data.text);
      data.sources.forEach((src) => finalCitations.add(src));
      decision_log.push(
        `Kept: "${data.text.slice(0, 60)}..." (${supportCount}/${totalModels} models agreed, avg confidence: ${(avgConfidence * 100).toFixed(0)}%)`
      );
    } else if (supportCount >= majorityThreshold && avgConfidence >= 0.5 && !hasCritiques) {
      finalClaims.push(data.text);
      data.sources.forEach((src) => finalCitations.add(src));
      decision_log.push(
        `Included: "${data.text.slice(0, 60)}..." (${supportCount}/${totalModels} models, high confidence: ${(avgConfidence * 100).toFixed(0)}%)`
      );
    } else if (supportCount >= 1 && avgConfidence >= 0.7 && !hasCritiques) {
      finalClaims.push(data.text);
      data.sources.forEach((src) => finalCitations.add(src));
      decision_log.push(
        `Included: "${data.text.slice(0, 60)}..." (single model, very high confidence: ${(avgConfidence * 100).toFixed(0)}%)`
      );
    } else {
      const reasons: string[] = [];
      if (supportCount < majorityThreshold) reasons.push(`only ${supportCount}/${totalModels} models`);
      if (avgConfidence < 0.6) reasons.push(`low confidence (${(avgConfidence * 100).toFixed(0)}%)`);
      if (hasCritiques) reasons.push(`${data.critiques.size} critique(s)`);

      decision_log.push(
        `Dropped: "${data.text.slice(0, 60)}..." (${reasons.join(", ")})`
      );

      if (supportCount === 1 && avgConfidence >= 0.7) {
        dissent.push({
          point: data.text,
          who: Array.from(data.supporters) as any[],
        });
      }
    }
  }

  const summary =
    finalClaims.length > 0
      ? finalClaims.join(" ")
      : "The AI models could not reach sufficient consensus on this question. Significant disagreement or low confidence prevented a unified answer.";

  let finalConfidence = 0;

  if (finalClaims.length > 0) {
    const finalClaimSet = new Set(finalClaims);
    const keptClaims = claimEntries.filter(([, data]) => finalClaimSet.has(data.text));

    const confidenceSum = keptClaims.reduce((sum, [, data]) => {
      const values = Array.from(data.confidences.values());
      return sum + values.reduce((a, b) => a + b, 0) / values.length;
    }, 0);

    const baseConfidence = keptClaims.length > 0 ? confidenceSum / keptClaims.length : 0;
    const consensusRatio = finalClaims.length / claimEntries.length;
    const consensusBonus = consensusRatio * 0.15;

    const totalCritiques = Array.from(allClaims.values()).reduce(
      (sum, data) => sum + data.critiques.size,
      0
    );
    const critiquePenalty = Math.min(0.3, totalCritiques * 0.03);

    finalConfidence = Math.min(1, Math.max(0, baseConfidence + consensusBonus - critiquePenalty));
  }

  // Build per-model comparison layer
  const finalClaimSet = new Set(finalClaims);
  const modelComparisons = buildModelComparisons(drafts, allClaims, finalClaimSet);

  return {
    summary,
    confidence: finalConfidence,
    citations: Array.from(finalCitations).slice(0, 10),
    decision_log,
    dissent,
    modelComparisons,
  };
}
